version: '3'

services:
  postgres:
    image: postgres:16
    container_name: goexpert_pg
    restart: unless-stopped
    environment:
      POSTGRES_USER: goexpert
      POSTGRES_PASSWORD: goexpert
      POSTGRES_DB: goexpert
    ports:
      - '5432:5432'
    volumes:
      - postgres-goexpert:/var/lib/postgresql/data
  migration:
    image: flyway/flyway:9.0
    command: -community -url=jdbc:postgresql://postgres:5432/goexpert -schemas=public -user=goexpert -password=goexpert -connectRetries=60 migrate
    volumes:
      - ./migration/flyway/sql:/flyway/sql
    depends_on:
      - postgres
volumes:
  postgres-goexpert: